# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [5]:
import numpy as np

In [1]:
import numpy as np

integers = np.array([1,2,3,4,5,6,7,8,9,10])

integers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
integers = np.arange(11)

integers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [11]:
numbers = np.array([[0,0,0], [0,0,0], [0,0,0]])

print(numbers)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
nums = np.zeros((3,3))
print(nums)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
numb = np.zeros((3,3), dtype=np.int)
print(numb)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

In [12]:
num = np.linspace(0,5,10)

print(num)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

In [16]:
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [17]:
B = np.random.rand(4,4)
B

array([[0.45304738, 0.71869634, 0.15827978, 0.88212097],
       [0.9880026 , 0.21647465, 0.87988031, 0.34726373],
       [0.6063153 , 0.92643807, 0.92566142, 0.9252013 ],
       [0.92469707, 0.98188596, 0.08247351, 0.29308271]])

In [19]:
C = np.random.random((4,4))
C

array([[0.85834572, 0.60572226, 0.93419578, 0.9074534 ],
       [0.22497863, 0.71628357, 0.51343165, 0.79667015],
       [0.08955671, 0.82442537, 0.2346931 , 0.44876643],
       [0.61236993, 0.03832674, 0.86784643, 0.78679196]])

In [20]:
np.random.seed(10)

In [22]:
d = np.random.rand(4,4)
d

array([[0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698, 0.51313824],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715]])

In [23]:
np.random.seed(0)

In [48]:
d = np.random.rand(4,4)
d

array([[0.4686512 , 0.97676109, 0.60484552, 0.73926358],
       [0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805]])

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

In [25]:
d.shape

(4, 4)

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [27]:
E = np.arange(16)
E

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
F = E.reshape((4,4))
F

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

In [30]:
F.dtype

dtype('int64')

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

In [34]:
G = np.arange(2,102,2)
G

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [33]:
#list
h = [x for x in np.arange(1,101) if x % 2 == 0]
h

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

In [35]:
I = np.random.randint(10, 50, (6,6))
I

array([[26, 15, 25, 10, 28, 45],
       [34, 39, 29, 29, 24, 49],
       [42, 11, 19, 42, 41, 20],
       [33, 45, 21, 38, 44, 10],
       [10, 46, 15, 48, 27, 25],
       [14, 41, 11, 11, 49, 45]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

In [39]:
J = np.random.randint(10, 20, (2,2))
J

array([[14, 16],
       [14, 14]])

In [40]:
j = J[:1]
print(j)

[[14 16]]


### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

In [52]:
help(np.sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

In [53]:
print(np.sum(d))

6.490685409741845


In [54]:
print(np.sum(F))

120


### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [60]:
#mean
np.mean(F)

7.5

In [61]:
#MEDIAN
np.median(F)

7.5

In [62]:
np.std(F)

4.6097722286464435

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [63]:
#Maximum value
np.max(F)

15

In [64]:
#Minimum value
np.min(F)

0

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [69]:
K = np.random.randint(10, 20, (20))
K

array([12, 13, 10, 10, 16, 10, 16, 13, 13, 18, 18, 18, 12, 13, 12, 10, 18,
       18, 13, 18])

In [70]:
np.argmax(K)

9

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

In [74]:
L = np.random.randint(1, 20, (20))
np.flip(L)

array([ 7,  5,  1,  9,  2, 17, 15, 17, 12, 14, 14, 12, 14,  4,  5,  1, 15,
       13,  4,  3])

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

In [77]:
M = np.random.randint(1, 20, (3,3))
N = np.random.randint(1, 20, (3,3))
print(M * N)

[[ 42  64  54]
 [ 36  15  48]
 [ 36  88 120]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

In [85]:
Q = np.random.randint(1, 20, (10))
print(Q)
np.diag(Q)

[17  4  8  4 19 18  2 19 18  3]


array([[17,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 19,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 18,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  2,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 19,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  3]])

In [86]:
q = np.random.randint(1, 20, (10))
print(q)
np.diag(q, k=2)

[ 6  6 13 13  3 16  8  8 12 18]


array([[ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 16,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [84]:
help(np.diag)

Help on function diag in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flattened input 

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

In [83]:
O = np.random.randint(1, 20, (2,2))
P = np.random.randint(1, 20, (2,2))
print("Matrix O = ", (O))
print("Matrix P = ", (P))
print("Matrix Multiplication")
print(np.dot(O,P))

Matrix O =  [[17  9]
 [ 2 18]]
Matrix P =  [[17  4]
 [ 9  5]]
Matrix Multiplication
[[370 113]
 [196  98]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

In [89]:
R = np.random.rand(2,2)
print(R)
np.ravel(R)

[[0.31179588 0.69634349]
 [0.37775184 0.17960368]]


array([0.31179588, 0.69634349, 0.37775184, 0.17960368])

In [88]:
help(np.ravel)


Help on function ravel in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changing
       

In [ ]:
### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

In [91]:
r = np.random.randint(1, 20, (3,3))
s = np.random.randint(1, 20, (3,3))
print(r)
print(s)
np.vstack((r,s))

[[15 10 19]
 [ 1 10 12]
 [18 10  1]]
[[17 11  5]
 [ 4  9 15]
 [ 1  9  8]]


array([[15, 10, 19],
       [ 1, 10, 12],
       [18, 10,  1],
       [17, 11,  5],
       [ 4,  9, 15],
       [ 1,  9,  8]])

Exercise 22:

Stack two NumPy arrays horizontally.

# Exercise 22


In [92]:
r1 = np.random.randint(1, 20, (3,3))
s1 = np.random.randint(1, 20, (3,3))
print(r1)
print(s1)
np.hstack((r1,s1))

[[14 18  1]
 [12  5  1]
 [11 15 19]]
[[ 5  4  8]
 [ 9 14  6]
 [ 1  9 16]]


array([[14, 18,  1,  5,  4,  8],
       [12,  5,  1,  9, 14,  6],
       [11, 15, 19,  1,  9, 16]])

In [90]:
help(np.vstack)

Help on function vstack in module numpy:

vstack(tup)
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays, will be at least 2-D.
    
    See Also
    --------
    concatenate : Join a sequence of arrays along an existing axis

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

In [11]:
T = np.random.randint(1, 20, (10,10))

print(T)
np.split(T, 5)

[[11  8  7  5 14 17  2  4 10  1]
 [ 6 18  4  3 11 16 11 10  6  9]
 [15 13 17  5  3  8 11  1  6 19]
 [15  1 12  6  2  9 14 10 10  8]
 [18 14  3 14  5  4  8 17 11 12]
 [ 1  4  8  3 13 19 12 13  7 10]
 [19 19  5 13 14  9  7 15 13  5]
 [ 1 18 19  4  1 19 13 16  7 15]
 [ 3 13 12 11  3  6  1  4  4  4]
 [14 13  4 16  7 10  9  7 13  5]]


[array([[11,  8,  7,  5, 14, 17,  2,  4, 10,  1],
        [ 6, 18,  4,  3, 11, 16, 11, 10,  6,  9]]),
 array([[15, 13, 17,  5,  3,  8, 11,  1,  6, 19],
        [15,  1, 12,  6,  2,  9, 14, 10, 10,  8]]),
 array([[18, 14,  3, 14,  5,  4,  8, 17, 11, 12],
        [ 1,  4,  8,  3, 13, 19, 12, 13,  7, 10]]),
 array([[19, 19,  5, 13, 14,  9,  7, 15, 13,  5],
        [ 1, 18, 19,  4,  1, 19, 13, 16,  7, 15]]),
 array([[ 3, 13, 12, 11,  3,  6,  1,  4,  4,  4],
        [14, 13,  4, 16,  7, 10,  9,  7, 13,  5]])]

In [7]:
help(np.split)


Help on _ArrayFunctionDispatcher in module numpy:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays as views into `ary`.

    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.

        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in

          - ary[:2]
          - ary[2:3]
          - ary[3:]

        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.

    Returns
    -------
    sub-arrays : list of ndarray

In [ ]:
### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

In [25]:
t = np.random.random((5,5))
np.round(t, decimals=2)

array([[0.18, 0.08, 0.99, 0.81, 0.54],
       [0.44, 0.38, 0.22, 0.67, 0.28],
       [0.94, 0.03, 0.82, 0.71, 0.83],
       [0.98, 0.15, 1.  , 0.56, 0.58],
       [0.28, 0.74, 0.43, 0.24, 0.85]])

In [14]:
help(np.round)

Help on _ArrayFunctionDispatcher in module numpy:

round(a, decimals=0, out=None)
    Evenly round to the given number of decimals.

    Parameters
    ----------
    a : array_like
        Input data.
    decimals : int, optional
        Number of decimal places to round to (default: 0).  If
        decimals is negative, it specifies the number of positions to
        the left of the decimal point.
    out : ndarray, optional
        Alternative output array in which to place the result. It must have
        the same shape as the expected output, but the type of the output
        values will be cast if necessary. See :ref:`ufuncs-output-type` for more
        details.

    Returns
    -------
    rounded_array : ndarray
        An array of the same type as `a`, containing the rounded values.
        Unless `out` was specified, a new array is created.  A reference to
        the result is returned.

        The real and imaginary parts of complex numbers are rounded
        separately

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

In [28]:
help(np.unique)

Help on _ArrayFunctionDispatcher in module numpy:

unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True)
    Find the unique elements of an array.

    Returns the sorted unique elements of an array. There are three optional
    outputs in addition to the unique elements:

    * the indices of the input array that give the unique values
    * the indices of the unique array that reconstruct the input array
    * the number of times each unique value comes up in the input array

    Parameters
    ----------
    ar : array_like
        Input array. Unless `axis` is specified, this will be flattened if it
        is not already 1-D.
    return_index : bool, optional
        If True, also return the indices of `ar` (along the specified axis,
        if provided, or in the flattened array) that result in the unique array.
    return_inverse : bool, optional
        If True, also return the indices of the unique array (for the specified
    

In [30]:
np.unique(T)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

In [34]:
n = 0.5
print(np.where(t < n, n, t))

[[0.5        0.5        0.9916969  0.80508578 0.54161074]
 [0.5        0.5        0.5        0.67064869 0.5       ]
 [0.94204191 0.5        0.81879364 0.70905524 0.83393271]
 [0.98265743 0.5        0.99667324 0.56132977 0.57732095]
 [0.5        0.73630759 0.5        0.5        0.85104341]]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

In [37]:
#t in question 26
np.sum(t)

13.730234714103434

In [ ]:
### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

In [42]:
U = np.random.randint(0, 20, (10,10))

print(U)
np.count_nonzero(U)

[[11  4 19  0 12 18 16 14  5 13]
 [ 0 11 12 11  1 11 18  3  1  6]
 [15 11 14 18  5  5 14 18  8 10]
 [16  1  5 11  6  2  0  9  4  7]
 [10 19  5  0  0  0  5 17 15 11]
 [ 4  0 11  3 13  3 16  6  8 16]
 [ 7 14  5 13  1 14  6 17 12 14]
 [18  5 14  5 17  9  3 14 19  4]
 [14 10 12 15  6 17  7 15  8 10]
 [ 1  6  8 10  7  9 11  4  4 13]]


93

In [40]:
help(np.count_nonzero)

Help on _ArrayFunctionDispatcher in module numpy:

count_nonzero(a, axis=None, *, keepdims=False)
    Counts the number of non-zero values in the array ``a``.

    The word "non-zero" is in reference to the Python 2.x
    built-in method ``__nonzero__()`` (renamed ``__bool__()``
    in Python 3.x) of Python objects that tests an object's
    "truthfulness". For example, any number is considered
    truthful if it is nonzero, whereas any string is considered
    truthful if it is not the empty string. Thus, this function
    (recursively) counts how many elements in ``a`` (and in
    sub-arrays thereof) have their ``__nonzero__()`` or ``__bool__()``
    method evaluated to ``True``.

    Parameters
    ----------
    a : array_like
        The array for which to count non-zeros.
    axis : int or tuple, optional
        Axis or tuple of axes along which to count non-zeros.
        Default is None, meaning that non-zeros will be counted
        along a flattened version of ``a``.

      

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

In [46]:
u = np.random.randint(1, 20, (10))

print(u)
np.sort(u)

[ 7  5 15  5  7 19  5  5 13  3]


array([ 3,  5,  5,  5,  5,  7,  7, 13, 15, 19])

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

In [56]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix
np.sum(matrix, axis=0)

array([12, 15, 18])

In [58]:
np.sum(matrix, axis=1)

array([ 6, 15, 24])

In [ ]:
### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

In [ ]:
### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

In [ ]:
### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

In [ ]:
### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

In [ ]:
---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

In [ ]:
### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

In [ ]:
---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

In [ ]:
---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

In [ ]:
---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

In [ ]:
---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

In [ ]:
---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

In [ ]:
---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

In [ ]:
---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

In [ ]:
---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---